#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 14 2022
@author: Sylvain Brisson sylvain.brisson@ens.fr

Tools to plot the green functions (from the files generated by green_extract)

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

import os
import argparse
import re

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument("--idtn", type=int, required=True)
    args = parser.parse_args()

    # getting green functions files

    files_S00 = pd.DataFrame(columns=['filename','angular_order'])
    files_S01 = pd.DataFrame(columns=['filename','angular_order'])
    files_S10 = pd.DataFrame(columns=['filename','angular_order'])
    files_S11 = pd.DataFrame(columns=['filename','angular_order'])
    files_T = pd.DataFrame(columns=['filename','angular_order'])

    comp_correspondance = {"00":files_S00, "01":files_S01, "10":files_S10, "11":files_S11, "5":files_T}

    green_file_re = r"green_+(?P<composante>\d{1,2})_l(?P<angular_order>\d{4})_(?P<idtn>\d)"

    print(">> Searching for green functions files")

    for f in os.listdir(os.getcwd()):

        search = re.search(green_file_re, f)
        if search:

            if int(search["idtn"]) == args.idtn:
                df = comp_correspondance[search["composante"]]
                df.loc[len(df.index)] = [f,int(search["angular_order"])]

    files_S00 = files_S00.sort_values("angular_order") 
    files_S01 = files_S01.sort_values("angular_order") 
    files_S10 = files_S01.sort_values("angular_order") 
    files_S11 = files_S11.sort_values("angular_order") 
    files_T = files_T.sort_values("angular_order") 

    # plotting 

    print(">> Plotting")

    titles = [
        "Spheroidal (00)",
        "Spheroidal (0+)",
        "Spheroidal (+0)",
        "Spheroidal (++)",
        "Toroidal",
    ]

    dfs = [
        files_S00,
        files_S01,
        files_S10,
        files_S11,
        files_T ,
    ]

    for df,title in zip(dfs,titles):

        cNorm  = matplotlib.colors.Normalize(vmin=df["angular_order"].min(), vmax=df["angular_order"].max())
        scalarMap = matplotlib.cm.ScalarMappable(norm=cNorm, cmap="gist_rainbow")

        fig,ax = plt.subplots(figsize=(12,8))

        for idx,row in df.iterrows():
            data = np.loadtxt(row['filename'])
            ax.plot(data[::2,0], data[::2,1],color=scalarMap.to_rgba(row["angular_order"]))
        
        plt.colorbar(scalarMap, label="Angular order")
        ax.set_title(title)
        ax.set_xlabel("Frequencie")
        ax.set_ylabel("Green function")

        outFile = title.replace(" ","_")+".png"
        print(f">> Saving {outFile}")
        fig.savefig(outFile,dpi=500,bbox_inches='tight')


